spring.application.name=rest-api-02
spring.datasource.url=jdbc:mysql://localhost:3306/ajpdb
spring.datasource.username=ajp
spring.datasource.password=sunbeam

spring.mvc.hiddenmethod.filter.enabled=true